Adding solve procedure with LAPACK support
chapel-lang/chapel pull request #16640
Opened 2020-10-30 11:06 UTC by CaptainSharf

2020-10-30 21:12 UTC, ben-albrecht requested changes
Thanks for contributing @CaptainSharf! Most comments made inline.

Regarding testing, I believe `performance/lu/lu-solve-test.chpl` will now default to the LAPACK version. In order to preserve that performance data, let's add a `performance/lu/lu-solve-test.compopts` that disables LAPACK, e.g. `-slapackImpl=off`. 

We also want to test the LAPACK version. I think we can do that by adding another entry to the `perfcompopts` file with `-slapackImpl=lapack`. I am not sure how that interacts with the existing `perfexecopts`, however. We will also need to add lapack variant to the `performance/linearalgebra-perf.graph`.

Give it a try and let me know if you run into any issues or have questions.

Minor comments:

- I suggest using `const` when a variable is not expected to change
- Try to make your coding style match the rest of the module
    - I mostly see inconsistencies with spacing. I've pointed out a few examples inline.

2020-10-30 21:12 UTC, ben-albrecht commented on modules/packages/LinearAlgebra.chpl
> +proc solve(A: [?Adom], B: [?Bdom]) where usingLAPACK{
Example of style variation from rest of module:

```suggestion
proc solve(A: [?Adom], B: [?Bdom]) where usingLAPACK {
```

2020-10-30 21:12 UTC, ben-albrecht commented on modules/packages/LinearAlgebra.chpl
> +      var B_mat :[1..rowsB,1..1] real;
Example of style variation from rest of module:

```suggestion
      var B_mat :[1..rowsB, 1..1] real;
```

2020-10-30 21:12 UTC, ben-albrecht commented on modules/packages/LinearAlgebra.chpl
> +  if(isSquare(A)){
Example of style variation from rest of module:

```suggestion
  if isSquare(A) {
```

2020-10-30 21:12 UTC, ben-albrecht commented on modules/packages/LinearAlgebra.chpl
> +      var rowsB = Bdom.size;
Example where we could use const:

```suggestion
      const rowsB = Bdom.size;
```

2020-11-01 09:08 UTC, CaptainSharf commented
Hi @bradcray ,
Thanks for the feedback! I'm trying to write performance tests for this method as you pointed out. Could you please point me towards how to execute performance tests, and verify the graphs?

2020-11-02 16:16 UTC, ben-albrecht commented
>  Could you please point me towards how to execute performance tests, and verify the graphs?

Run `start_test --performance lu-solve-test.chpl` and then `start_test --gen_graphs`. It will print out a path which will contain an HTML file you can view in your browser.

2020-11-02 16:17 UTC, ben-albrecht commented
The [test docs](https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/TestSystem.rst#a-performance-test) are a good reference as well.

2021-04-07 20:32 UTC, ben-albrecht commented
@CaptainSharf - I am revisiting some old open PRs. I think this is a great feature to have, but I am going to close this PR due to inactivity for now. We'll reopen when you get a chance to resume development.

2021-04-07 20:32 UTC, closed without merging

2021-04-08 08:44 UTC, CaptainSharf commented
Thanks @ben-albrecht !
I wish to revisit this feature at some point in the near future. This PR is missing performance tests