Issue #17136: Changes to choice method of Random module to support sampling on N-Dimensions
chapel-lang/chapel pull request #17168
Opened 2021-02-15 04:19 UTC by prashanth018

Changes to choice method of Random module to support sampling on N-Dimensional Array/Domain. Also have added few test cases (need to refine). Existing tests run without any issues.

2021-06-22 03:27 UTC, bradcray commented
Hi @prashanth018 : I'm cleaning out old pull requests, and am noticing that this one has received no attention.  Did you reach out to the team to ask for a review?  (we often don't notice PRs unless someone brings them to our attention due to the number that are open at any given time).  Thanks for any information.

2021-06-22 13:18 UTC, prashanth018 commented
Hi @bradcray, Yes I did reach out and it was apparent and understandable that most of the reviewers were busy with the release. It would be good if one of you could take a look at it. Also, given that I'm already working on my GSoC project, there might be few delays in merging this issue. Thanks. :)

2021-07-07 23:12 UTC, e-kayrakli requested changes
Thanks @prashanth018! Please see my in-line comments.

2021-07-07 23:12 UTC, e-kayrakli commented on modules/standard/Random.chpl
> +  }
Reading the code a bit more, I'd remove both of these helpers, and add a type function helper like

```chapel
private proc _choiceIndexTypeHelper(X: domain) type {
  return if X.rank == 1 then int else X.rank*int;
}
```

(I'm not a big fan of the preceding `_`, but that's how similar functions are named, and let's be consistent)

And then change the array declarations where you're currently using these functions as

```chapel
var a: [b] _choiceIndexTypeHelper(X);
```

and such.

2021-07-07 23:12 UTC, e-kayrakli commented on modules/standard/Random.chpl
> +    ref P = reshape(prob, {0..<X.size});
I don't have a problem with this, but, is there any reason you are not keeping the previous idiom? (`prob.reindex(bla)`)

2021-07-07 23:12 UTC, e-kayrakli commented on modules/standard/Random.chpl
> +     :arg prob: an optional N-D array that contains probabilities of choosing
I think we can remove dimensionality from all these statements. `an optional array` is sufficient, to me.

2021-07-07 23:12 UTC, e-kayrakli commented on test/library/standard/Random/RandomStreamInterface/choiceTestUtils.chpl
> +                      else reshape(prob, {1..X.size});
I am seeing a similar change here, so there must be something that I am missing that makes this necessary.

2021-07-07 23:12 UTC, e-kayrakli commented on test/library/standard/Random/RandomStreamInterface/choiceTestUtils.chpl
> +  else if X.rank > 1 {
Could you at least add a comment here saying that if we're hitting this `if`, `X` must be domain? You can also make the code more self-documenting by 

```chapel
else if isDomainValue(x) {
  if X.rank > 1 {

  }
  else {

  }
}
else {
  compilerError("Unexpected type");
}

2021-07-07 23:12 UTC, e-kayrakli commented on modules/standard/Random.chpl
> +  use ChapelArray;
Why did we need this?

2021-11-29 23:13 UTC, e-kayrakli commented
@prashanth018 -- as you've been silent here and in your other PRs, I am going to go ahead and close this. You're more than welcome to reopen if/when you want to revisit this.

2021-11-29 23:13 UTC, closed without merging