List.append() returns index of inserted element
chapel-lang/chapel pull request #17510
Opened 2021-04-02 07:38 UTC by strikeraryu

I have added the functionality to return the index of the inserted element Introduced in Issue #17466. Currently, I have made changes in List.chpl.
Further changes can be made regarding documentation and testing.

2021-04-02 14:19 UTC, bradcray commented
@strikeraryu : You should also add a new test that locks in this change to make sure it doesn't break in the future.  This can be done in `test/library/standard/List/`.  See https://github.com/chapel-lang/chapel/blob/master/doc/rst/developer/bestPractices/TestSystem.rst for more information on the Chapel test system if you haven't used it before.

2021-04-02 14:22 UTC, strikeraryu commented
Should I make the test for both serial and parallel cases?

2021-04-02 14:24 UTC, bradcray commented
> Should I make the test for both serial and parallel cases?

Good question.  I think that would be ideal, though writing deterministic parallel tests can be challenging.  Though perhaps an approach would just be to have a number of tasks call insert() with a unique integer simultaneously, store the index they got back into a normal array, and then have a serial task after the parallel section run through that array verifying that the expected integer is at the expected list index?

2021-04-02 14:31 UTC, strikeraryu commented
I wrote a test to check manually for parallel before (mentioned in issue #17466) 
``` chapel
coforall i in 0..10 with (ref l){
    var ind = l.append(i);
    writeln(ind, " ", i);
}
writeln(l);
```
can I update this to make it automated?

2021-04-02 14:36 UTC, bradcray commented
Ideally, you wouldn't want to print within the parallel loop, or print out the list elements since the output order will be nondeterministic across runs, so would be hard to embed in a .good file within the test system (without post-processing).  This is why I was suggesting storing the `ind` values into an array indexed by `i` where the array is declared outside the loop. 
 Then you can check after the loop that `l[arr[i]] == i;` for each i in 0..10, printing success or failures/assertion errors and having the .good file just contain the success output (since it should always be true).

2021-04-02 14:44 UTC, strikeraryu commented
Yeah, that was for just checking manually. I will automate this by the ways you mentioned, Thanks.

2021-04-02 19:23 UTC, strikeraryu commented
I have added the test for both serial and parallel, Should I update the documentation with the changes done in ```list.append()```.

2021-04-02 19:25 UTC, dlongnecke-cray commented
Updating the documentation would be great, thanks!

2021-04-02 19:26 UTC, strikeraryu commented
What are the main files concerning the documentation?

2021-04-02 19:33 UTC, dlongnecke-cray commented
You'll want to update the docstring on `list.append()` to mention that it returns the indice of the appended element. You can check your changes to the docs with something like:

```
cd $CHPL_HOME
make docs
cd doc/html
python3 -m http.server
```

Then in your browser head to `localhost:8000`, navigate to `Standard Modules` -> `List`, and check out how your changes look in the rendered documentation for `list.append()`.

2021-04-02 21:13 UTC, bradcray commented
> You'll want to update the docstring on list.append()

Just in case this isn't crystal clear to @strikeraryu (it wouldn't have been to me a few years ago), the documentation is generated from the comments that precede the routine in the source code.  The `make docs` step that David outlines above will generate the docs from the source.  I don't personally tend to spin up a server to view them, but just point a browser at `$CHPL_HOME/docs/html/index.html` and go from there (as simple as `open docs/html/index.html` on a Mac).

2021-04-02 21:26 UTC, strikeraryu commented
I am getting error while ```make docs```, is there a recent change related to this, as my local branch is behind.

2021-04-02 21:36 UTC, bradcray commented
> I am getting error while make docs, is there a recent change related to this, as my local branch is behind.

There shouldn't be... what kind of error?

2021-04-02 21:51 UTC, strikeraryu commented
I dont remember the error exactly but it was somethin related to make error in man and then there was no html file in doc folder. I doing some changes, if i get same error again I send the exact error.

2021-04-02 22:58 UTC, bradcray commented
Hmm, that one is not at all familiar to me, and I'm not much of a Python guru, which is where the problem seems to be.  This might be worth opening a new issue for, or asking about on Discourse or Gitter, as I believe it's independent of your effort here.  My first reaction is "Could something be wrong with your Python installation?  Could re-installing Python fix it?" but that's a shot in the dark.

Since it looks to be specific to making the man pages, and you're not working there at the moment, it might be worth editing your copy of `Makefile.devel` to remove the `man-*` dependencies in the `docs:` rule and just focus on the chpldoc docs.  (Of course, if something's wrong with your Python setup, you may hit different issues, but that could be interesting as well).

2021-04-04 16:23 UTC, strikeraryu commented
> it might be worth editing your copy of Makefile.devel to remove the man-* dependencies in the docs: rule and just focus on the chpldoc docs.

while trying out this I got this error
![image](https://user-images.githubusercontent.com/37619410/113515130-3ca1d480-9590-11eb-87e8-8069275876f2.png)

2021-04-04 19:34 UTC, strikeraryu commented
It finally worked for me, and I think we are good to go. I edited the docstring for ```List.append()``` when is first edited the function but now I have tested and it is giving the right details.
![image](https://user-images.githubusercontent.com/37619410/113519563-b3e46200-95aa-11eb-9c1d-cfdd43a8a0db.png)

2021-04-05 16:21 UTC, bradcray commented
@dlongnecke-cray : Do you have time to review this PR due to your familiarity with the List module?

2021-04-05 17:06 UTC, dlongnecke-cray commented
Yes, I will review it.

2021-04-08 02:11 UTC, dlongnecke-cray requested changes
Go ahead and check the updated docs locally to make sure they look OK.

In the OP, mention:

- What testing you've done (e.g., you checked the docs, maybe ran the tests in `test/library/standard/List`
- Add a "Resolves #17466" so that the issue will auto close after this pull is merged

I'll check out the branch and start running tests. Thanks!

2021-04-08 02:11 UTC, dlongnecke-cray commented on modules/standard/List.chpl
> +      var insertedElementIndex = _size - 1;
Let's go ahead and rename `insertedElementIndex` to `result` to stay consistent with the rest of the module.

2021-04-08 02:27 UTC, bradcray commented
> Go ahead and check the updated docs locally to make sure they look OK.

David: Doesn't the screen shot above already demonstrate that they do?

2021-04-08 02:46 UTC, dlongnecke-cray commented
Haha that's what I get for only looking on the `Files` tab!

2021-04-08 04:02 UTC, dlongnecke-cray commented
Hi @strikeraryu, there were some test failures. Mind taking a look?

```
[Test Summary - 210407.223805]
[Error matching compiler output for classes/delete-free/lifetimes/bad-append-borrow]
[Error matching compiler output for library/standard/List/classLists/listAppendBorrow]
[Error matching compiler output for library/standard/List/classLists/listAppendLifetime]
[Error matching program output for library/standard/List/listAppendLifetime]
[Summary: #Successes = 12599 | #Failures = 5 | #Futures = 0]
[END]
```

2021-04-08 16:44 UTC, bradcray commented
@dlongnecke-cray / @strikeraryu : I was surprised that anything would fail under this PR, so checked the branch out to reproduce and am seeing that we're not getting the same lifetime errors from `append()` as we did prior to this change.  I'm trying to guess whether that implies there's a pre-existing bug here, or whether something about making the method return changes the semantics or abilities of the lifetime checker.  Tagging @mppf in case it's more obvious to him that to us.

(sample diffs for anyone not wanting to bother building the branch:  The lifetime errors embedded in the `.good` files due to the append() calls are not present in the output now, e.g.:

```diff
[Executing diff listAppendBorrow.good listAppendBorrow.comp.out.tmp]
1,5d0
< listAppendBorrow.chpl:16: In function 'error7':
< listAppendBorrow.chpl:17: error: Actual argument does not meet called function lifetime constraint
< listAppendBorrow.chpl:16: note: consider scope of arg
< $CHPL_HOME/modules/standard/List.chpl:nnnn: note: called function list(borrowed foo?,false).append(x: borrowed foo?)
< $CHPL_HOME/modules/standard/List.chpl:nnnn: note: includes lifetime constraint this < x
```

2021-04-08 16:57 UTC, mppf commented
> I'm trying to guess whether that implies there's a pre-existing bug here, or whether something about making the method return changes the semantics or abilities of the lifetime checker. Tagging @mppf in case it's more obvious to him that to us.

Unfortunately this sounds like a bug in the lifetime checker. The `lifetime this < x` constraint should cause the error, no matter the return type.

2021-04-08 16:59 UTC, strikeraryu commented
I was going through this and I was getting the same error, so started looking about lifeline in Chapel, I was not able to understand the problem because I am neither returning a reference nor storing a variable with local scope into a variable with a larger scope.

2021-04-08 17:22 UTC, dlongnecke-cray commented
I will see if I can find a reproducer to fix this bug/look for a quick fix.

2021-04-09 04:52 UTC, dlongnecke-cray commented
I haven't quite found a fix yet, so my plan is to go ahead and merge your work @strikeraryu and then deal with the fallout later by adding a future or two. My rationale is that that the test failures arguably uncovered a bug that we wouldn't have found otherwise (so extra props in that regard)!

So sometime tomorrow I'll be hitting the merge button 👍.

2021-04-09 04:57 UTC, strikeraryu commented
Great, you can tell me if you want me for anything, Thanks.

2021-04-09 16:51 UTC, merged

2021-04-09 16:51 UTC, dlongnecke-cray commented
Thanks @strikeraryu!

2021-04-14 04:25 UTC, bradcray commented
@dlongnecke-cray : Weird... when I `git log` this PR, I get the log message:

```
Merge pull request #17510 from strikeraryu/master

Added a const ref overload to the methods first() and last() using
helpers. Previously the methods did not accept the usage of const
ref intent types.

Resolves #17259

-

Contributed by @strikeraryu, reviewed by @dlongnecke-cray.

[Reviewer comments follow...]

Tested with COMM=none and COMM=gasnet runs. Checked docs locally.

Several lifetime checker tests related to `list` will fail as a
consequence of merging this PR. They are not a result of this effort
but rather a bug that changing the return type of `list.append()`
from `void` to `int` has uncovered.

I will open a PR addressing test failures and adding futures as a
separate effort.

Thanks @strikeraryu!
```

cut-and-paste error?

2021-04-14 05:57 UTC, dlongnecke-cray commented
No, that is the merge commit exactly as I formatted it. The lines above the `-` are intended to be the user's merge commit exactly as they wrote it. The lines below the `-` are my comments.

2021-04-14 06:02 UTC, bradcray commented
Isn't this the PR that made list.append() return the index of the new element?  Looking at the file diffs, first/last seem untouched, and the OP says:

```
List.append() returns index of inserted element

I have added the functionality to return the index of the inserted element Introduced in Issue #17466. Currently, I have made changes in List.chpl.
Resolves #17466

Further changes can be made regarding documentation and testing.
```

2021-04-14 06:04 UTC, dlongnecke-cray commented
I'm timing out from thinking about closures today. You're correct that the message is a typo. I must have copied the wrong OP without checking it twice.

2021-04-14 06:08 UTC, bradcray commented
No problem (and I don't think it's worth fixing), I just noticed it while surfing through git logs and writing up status reports.

2021-04-14 06:24 UTC, strikeraryu commented
Should I mention this in OP so if someone comes looking in the future he realizes quickly that it was just a typo, or is it ok as it is?

2021-04-14 06:34 UTC, bradcray commented
Thanks for asking, @strikeraryu.  I think we're good with this comment trail.