Chapel 1.25 contributors file
chapel-lang/chapel pull request #18372
Opened 2021-09-08 20:24 UTC by bradcray

This is a rough draft currently...  needs more eyes on it.

2021-09-08 20:53 UTC, bradcray commented
@VisionTheta , @strikeraryu, @shubhamkmr04, @king-11, @Yudhishthira1406 , @prashanth018 : Would you make sure I spelled and formatted your names correctly?

@king-11, @Yudhishthira1406 , @prashanth018: Would you also make sure I got your schools' names and hyperlinks correct?

@chapel-lang/core-contributors :
* If you're a new hire, please make sure I didn't mis-spell your name (or simply got it wrong... it's happened).
* If you merged changes from an external contributor for 1.25, please make sure they're credited here.

2021-09-08 21:54 UTC, lydia-duncan commented
I think you're missing @Venkatavaradan-R

2021-09-08 22:12 UTC, bradcray commented
Huh, that's odd... I primarily base my edits on https://github.com/chapel-lang/chapel/graphs/contributors?from=2020-12-15&to=2021-09-08&type=c and Venkat's name doesn't show up there for some reason.  For reference, we're talking about:
* https://github.com/chapel-lang/chapel/pull/17397
* https://github.com/chapel-lang/chapel/pull/17421
right?

2021-09-08 22:25 UTC, bradcray commented on CONTRIBUTORS.md
> -* Yujia Qiao, [GSoC 2020] student from [Huazhong University of Science and Technology]
Thanks for catching this, Engin.  It looks like the March-today view I was using only covers commits made, not when those commits were merged, which is why I missed this one.  Apologies, @king-11 !

2021-09-09 00:10 UTC, prashanth018 requested changes
Could you change it to "Prasanth" instead of "Prashanth". Thanks.

2021-09-09 00:24 UTC, bradcray commented
@prashanth018 : Sure thing.

2021-09-09 01:16 UTC, shubhamkmr04 commented
> @VisionTheta , @strikeraryu, @shubhamkmr04, @king-11, @Yudhishthira1406 , @prashanth018 : Would you make sure I spelled and formatted your names correctly?
> 
> @king-11, @Yudhishthira1406 , @prashanth018: Would you also make sure I got your schools' names and hyperlinks correct?
> 
> @chapel-lang/core-contributors :
> 
> * If you're a new hire, please make sure I didn't mis-spell your name (or simply got it wrong... it's happened).
> * If you merged changes from an external contributor for 1.25, please make sure they're credited here.

Yes, My name is correct in this. Thanks!

2021-09-09 01:33 UTC, VisionTheta commented
> @VisionTheta , @strikeraryu, @shubhamkmr04, @king-11, @Yudhishthira1406 , @prashanth018 : Would you make sure I spelled and formatted your names correctly?
> 
> @king-11, @Yudhishthira1406 , @prashanth018: Would you also make sure I got your schools' names and hyperlinks correct?
> 
> @chapel-lang/core-contributors :
> 
> * If you're a new hire, please make sure I didn't mis-spell your name (or simply got it wrong... it's happened).
> * If you merged changes from an external contributor for 1.25, please make sure they're credited here.

Yes, my name is also correct, thank you.

2021-09-09 14:58 UTC, lydia-duncan commented
> Huh, that's odd... I primarily base my edits on https://github.com/chapel-lang/chapel/graphs/contributors?from=2020-12-15&to=2021-09-08&type=c and Venkat's name doesn't show up there for some reason. For reference, we're talking about:
> 
>     * [Fixed minor formatting bug in primers/classes #17397](https://github.com/chapel-lang/chapel/pull/17397)
> 
>     * [Removed syntax highlighting for list of keywords in lexical-structure.rst #17421](https://github.com/chapel-lang/chapel/pull/17421)
>       right?

Yup, that's right!  I think that view tends to be sensitive to things like the email address used when making the commit - when someone on the team leaves and changes the email address associated with their account, we tend to not see commits they've made in that view with that old email address any more

2021-09-09 20:02 UTC, mppf commented
Looks like we need to add Mohaned Mashaly @12mohaned for PR #17470.

2021-09-09 22:18 UTC, bradcray commented
@mppf, @lydia-duncan, @e-kayrakli : I think I've fixed the oversights you noted.

@Venkatavaradan-R , @12mohaned , @prashanth018 : If you could check that I've got your name right / as you like it, that would be great.  Thanks!

2021-09-10 17:07 UTC, bradcray commented on CONTRIBUTORS.md
> +* Lakshya Singh, [GSoC 2021] student from [Indian Institute of Technology (BHU)]
No problem, Lakshya, and thanks for correcting me.  I'd seen it on their webpage, but went with what I was seeing on your pages.  Check that I got it right, if you would.

2021-09-10 18:20 UTC, king-11 commented on CONTRIBUTORS.md
> +* Lakshya Singh, [GSoC 2021] student from [Indian Institute of Technology (BHU)]
Yes now its the correct one thanks

2021-09-11 16:39 UTC, bradcray commented
@vrockz747 : Would you make sure I've got your name right?

2021-09-14 20:52 UTC, merged