Try with just Push option to see if email step is triggered
chapel-lang/chapel pull request #20833
Opened 2022-10-12 17:11 UTC by bhavanijayakumaran

2022-10-12 18:51 UTC, bhavanijayakumaran commented on .github/workflows/email.yml
> +     # - main
Commented out to see if this works when we merge a PR to main from forked repository.
If this patch works will remove this commented line.

2022-10-12 18:51 UTC, bhavanijayakumaran commented on .github/workflows/email.yml
> +    #if:  github.event.pull_request.merged == false
Commented out to see if this is what is causing the email step to be skipped. 
Will remove this line if this dix works in a followup review.

2022-10-12 21:51 UTC, bhavanijayakumaran commented
Tried closing a PR with close filter and it works as expected.

https://github.com/bhavanijayakumaran/chapel/actions/runs/3238100043

2022-10-13 14:59 UTC, riftEmber requested changes
As far as I can tell this will trigger on a PR that is closed even if it is not merged, which I don't think is what we want. I think the `if_merged` step you wrote has the right idea and that kind of conditional could be used to avoid sending the email if it is not a merge.

Additionally, it looks like Elliot's suggestion in https://github.com/chapel-lang/chapel/pull/20794#discussion_r991582020 to remove some extra newlines didn't make it in -- I would like to echo that suggestion as I also think it would be good for readability to cut down on the extra line breaks.

2022-10-13 15:59 UTC, bhavanijayakumaran commented
@riftEmber I have checks to check for both closed and merged. 

name: email
on:
    pull_request:
      types:
        **- closed**   
jobs:
  
  send_email:
   # run this workflow step only when the PR is merged 
    if:  **github.event.pull_request.merged == true** 
    runs-on: ubuntu-latest
    
    I will remove the extra new lines.

2022-10-13 16:31 UTC, riftEmber approved these changes
Sorry, missed the condition on the job as a whole. Looks good!

2022-10-13 16:34 UTC, bhavanijayakumaran commented
Np @riftEmber. Thanks for the review!

2022-10-13 16:36 UTC, merged

2022-10-13 16:44 UTC, bhavanijayakumaran commented
Ok, the email workflow is triggered but the actions secrets are not available for git workflow.

I will try to fix it, if it takes a while I will just revert the PR.
https://github.com/chapel-lang/chapel/actions/runs/3244107990/jobs/5319807737