Replace sprintf with snprintf in the runtime
chapel-lang/chapel pull request #21021
Opened 2022-11-09 19:31 UTC by jhh67

Replace `sprintf` with `snprintf` in the runtime

Resolves https://github.com/Cray/chapel-private/issues/3996.

2022-11-09 20:12 UTC, riftEmber requested changes
For consistency and to future proof against warnings/strict standards, I think we should stick to feeding in a `size_t` to `snprintf`, either by casting or multiplying by `sizeof(char)` as appropriate. I've marked all occurences I found where it gets an `int` instead.

2022-11-09 20:12 UTC, riftEmber commented on runtime/src/chpl-launcher-common.c
> +    snprintf(evList, evListSize, "%s=%s", evName, evVal);
here

2022-11-09 20:12 UTC, riftEmber commented on runtime/src/chpl-launcher-common.c
> +    snprintf(evList + evListSizeWas - 1, evListSize - (evListSizeWas - 1),
here

2022-11-09 20:12 UTC, riftEmber commented on runtime/src/chpl-string-support.c
> +  snprintf(buffer, 2, "%c", x[i-1]);
here (maybe this one doesn't count as it's a literal? not sure)

2022-11-09 20:12 UTC, riftEmber commented on runtime/src/chplmemtrack.c
> +      snprintf(filename, size, "%s.%" PRI_c_nodeid_t, memLog, chpl_nodeID);
here, although we multiply by `sizeof(char)` when declaring `size` it it declared as an `int`

2022-11-09 20:12 UTC, riftEmber commented on runtime/src/chplmemtrack.c
> +  int locSize = (filenameWidth+numberWidth+1)*sizeof(char);
here, for use in both `sys_malloc` and `snprintf` below

2022-11-09 20:12 UTC, riftEmber commented on runtime/src/launch/pbs-aprun/launch-pbs-aprun.c
> +    snprintf(qsubFilename, qsubFilenameSize, "qsub.%s-%d", genFilename,
here (`size_t` stored into an `int`)

2022-11-09 20:12 UTC, riftEmber commented on runtime/src/launch/slurm-gasnetrun_common/slurm-gasnetrun_common.h
> +    len += snprintf(buf, size, " -E '%s'", enviro_keys);
here

2022-11-09 20:12 UTC, riftEmber commented on runtime/src/launch/slurm-srun/launch-slurm-srun.c
> +  snprintf(command, size, "%s", baseCommand);
here

2022-11-09 23:01 UTC, riftEmber approved these changes
thanks!

2022-11-10 13:43 UTC, merged

2022-11-15 03:06 UTC, bradcray commented
Thanks John!