Range+domain doc minor improvements
chapel-lang/chapel pull request #23664
Opened 2023-10-17 01:36 UTC by vasslitvinov

Unstabilize `range.strType` belatedly, as we have not approved it for the stable interface for ranges.

Remove from the spec the configs `noNegativeStrideWarnings`, `newSliceRule`, and `newRangeLiteralType` because they are purely implementation-specific.

Also remove from the spec the domain initializers because users are not supposed to write `new domain(....)`, and also the domain methods `this` and `these` because they are presented as slicing and as iteration over domains, respectively.

Add or adjust some comments.

Move the chpldoc for `domain.clear` to the overload without the where-clause. Previously the online docs for `domain.clear` showed a where-clause unnecessarily.

2023-10-17 21:46 UTC, dlongnecke-cray requested changes
I think we should end all the doc comments with periods (or have them all not end with a period) just to be consistent.

2023-10-17 21:46 UTC, dlongnecke-cray commented on modules/internal/ChapelDomain.chpl
> +    /* Return the domain map that implements this domain */
End with period?

2023-10-18 02:55 UTC, vasslitvinov commented
@dlongnecke-cray I added a bunch of missing periods and switched from "return" to "returns". How does it look to you now?

2023-10-18 21:50 UTC, dlongnecke-cray approved these changes

2023-10-18 23:47 UTC, merged