Improve index-neutrality of `LinearAlgebra`
chapel-lang/chapel pull request #23852
Opened 2023-11-15 14:00 UTC by Guillaume-Helbecque

This PR is part of #17624 and improves the index-neutrality (any offset) of the following procedures:
- `solve_tril`
- `solve_triu`
- `solve`
    - private `_lu`
    - private `permute`
- `lu` (implicitly)
- `det` (implicitly)

It also adds several correctness tests.

Resolves #17513

2023-11-17 10:47 UTC, Guillaume-Helbecque commented
The correctness tests added in this PR are derived from the long-time pending PR #17558.

2023-11-17 11:01 UTC, Guillaume-Helbecque commented
**Note:** Working on this PR, I identified some issues that could be solved in follow up PRs:

- `solve_*` methods doesn't work when arrays contain `int`, due to integral division;
- I wonder why the `solve_tril` method has a `unit_diag` argument, while the `solve_triu` doesn't have. It seems that the latter has been introduced for performance reason, but removing it should make no difference. In addition, `solve_tril` is mainly called inside `solve`, which doesn't set `unit_diag`;
- We could benefit from minor performance improvements by decomposing some loops. For example in `solve_tril`:
```chapel 
for i in first..last {
    const sol = if unit_diag then y(i) else y(i) / L(i,i);
    y(i) = sol;

    if (i < last) {
      forall j in (i+1)..last with (ref y) {
        y(j) -= L(j,i) * sol;
      }
    }
  }
```
The `if`-statement is repeated each iteration, but is satisfied for only once (for `i = last`). This could cause performance degradation when the array size is large. We could rewrite this as:
```chapel 
for i in first..(last-1) {
    const sol = if unit_diag then y(i) else y(i) / L(i,i);
    y(i) = sol;

    forall j in (i+1)..last with (ref y) {
      y(j) -= L(j,i) * sol;
    }
  }
const sol = if unit_diag then y(last) else y(last) / L(last,last);
y(last) = sol;
```

2023-12-08 16:15 UTC, jeremiah-corrado requested changes
Hi @Guillaume-Helbecque, these changes look good!

Just one note about the `permute` procedure:

2023-12-08 18:38 UTC, jeremiah-corrado commented on modules/packages/LinearAlgebra.chpl
> +  var B: [dim] eltType;
Hmm, I didn't realize it was private and only used in the 1D case. I'd be inclined to remove the 2D branch of that procedure then (where we could always add it back later on if a use case arose).

2023-12-11 22:17 UTC, jeremiah-corrado approved these changes
Hi @Guillaume-Helbecque, looks good!

Let me run our test suite on your branch one more time and then I'll merge if there aren't any issues.

2023-12-11 22:58 UTC, merged

2023-12-12 11:58 UTC, Guillaume-Helbecque commented
Hi @jeremiah-corrado, thanks for merging. Could you please edit the initial comment in #17624 in order to reflect this PR?

2023-12-12 15:51 UTC, jeremiah-corrado commented
Sure, it's been updated. Thanks again for contributing!