Remove CHPL_NIGHTLY_CRON_RECIPIENT from the test scripts
chapel-lang/chapel pull request #23907
Opened 2023-11-27 14:57 UTC by bhavanijayakumaran

Address https://github.com/Cray/chapel-private/issues/5606
Remove nightly email env from the test script.

2023-11-29 15:50 UTC, tzinsky approved these changes

2023-11-29 16:25 UTC, riftEmber requested changes
`util/buildRelease/testRelease` also contains use of `CHPL_NIGHTLY_CRON_RECIPIENT` which should be removed

2023-11-29 16:25 UTC, riftEmber commented on doc/rst/developer/bestPractices/NightlyTesting.rst
There is another reference to `CHPL_NIGHTLY_CRON_RECIPIENT` on line 19

2023-11-30 16:35 UTC, bhavanijayakumaran commented on doc/rst/developer/bestPractices/NightlyTesting.rst
Removed

2023-11-30 19:33 UTC, bhavanijayakumaran commented
> There is still the uses of the variable in `util/buildRelease/testRelease` that should be removed -- could use grep to avoid missing any

Removed all the references in commit #4

2023-12-01 18:45 UTC, merged