Update docs for Chapel enviroment variables
chapel-lang/chapel pull request #25212
Opened 2024-06-11 00:33 UTC by jabraham17

2024-06-11 00:44 UTC, bonachea requested changes

2024-06-11 00:44 UTC, bonachea commented on doc/rst/usingchapel/chplenv.rst
> +       system   use a system install of hwloc (requires version 2.1+)
The sentence above this table also needs to be updated to reflect the fact there are now 3 options.

2024-06-11 00:44 UTC, bonachea commented on doc/rst/usingchapel/chplenv.rst
> +          system   use the jemalloc found on the system
The sentence above this table also needs to be updated to reflect the fact there are now 3 options.

2024-06-12 19:07 UTC, jhh67 approved these changes

2024-06-12 20:33 UTC, bonachea approved these changes

2024-06-12 21:56 UTC, merged