Raise number of threads used by GASNet by default + add warning if exceeded
chapel-lang/chapel pull request #26448
Opened 2024-12-21 01:34 UTC by bradcray

As noted in https://github.com/chapel-lang/chapel/issues/26379, we've recently had a user on a high-core-count system get surprised when we quietly dialed the maximum number of tasks down to 255 rather than using the number of cores on that system.  This PR addresses that issue in two ways:

* by inserting a warning if/when this happens so that the user can be aware that it is happening (it's admittedly not a very good warning, but it's also now even less likely that it will occur, because we also…)
* by raising the number of threads that GASNet is configured with to 65535 as suggested by @bonachea in https://github.com/chapel-lang/chapel/issues/26379#issuecomment-2529688584, which will result in 1024 being used as the default limit

While here, I also noticed that we seemed to be passing the list of GASNet configuration options to it twice, introduced in 2014 in d76598295b5.  I don't see any indication that that's any more than a typo, so here, I've removed one of the occurrences, leaving the one at the end of the line there, thinking it'd support overriding other, earlier options.

2024-12-21 03:48 UTC, bonachea reviewed
Thanks for the fixes!

Made a few minor observations, in case they're helpful.

2024-12-21 03:48 UTC, bonachea commented on runtime/src/tasks/qthreads/tasks-qthreads.c
> +            chpl_warning(msg, 0, 0);
New warning text LGTM, and should usually achieve the goal of avoiding silent under-utilization of cores.

However IIUC the new warning won't be printed on a heterogeneous system where node 0 has a smaller core count than `maxThreads`, but some other node might have a higher core count.

Not sure if such node heterogeneity is of interest (or even permitted by Chapel?) so feel free to ignore this observation if it seems irrelevant or not worth addressing.

2024-12-21 03:48 UTC, bonachea commented on third-party/gasnet/Makefile
> +	$(ENSURE_GASNET_COMPATIBLE_COMPILER) cd $(GASNET_BUILD_DIR) && $(CHPL_GASNET_ENV_VARS) $(GASNET_SUBDIR)/$(CHPL_GASNET_CFG_SCRIPT) --prefix=$(GASNET_INSTALL_DIR) --disable-seq --enable-par --disable-
This hunk partially overlaps the same fix proposed in the first commit of #25414 for the same cosmetic defect.

It sounds like we both independently made the same observation about the GASNet configure line and arrived at the same fix, so feel free to close #25414 in favor of this PR.

2025-01-15 18:50 UTC, bradcray commented on runtime/src/tasks/qthreads/tasks-qthreads.c
> +            chpl_warning(msg, 0, 0);
@bonachea : I'm finally finding my way back to this PR.  Thanks for the quick look and comments, and sorry not to have acknowledged them before now.

Chapel doesn't worry overmuch about node heterogenity [anymore], primarily because peoples' questions about it seem to typically be academic.  That said, I'm also not interested in making things worse/harder for node heterogeneity than they are, so am still weighing the question seriously.

I'm 96% certain that this runtime startup code is executed in an SPMD manner (one process per locale), so would expect this logic to fire on every locale, and therefore to potentially take different actions on different locales.  To check that theory, I put a printf() into the code here, ran a hello world on 4 locales, and got the message printed 4 times.  Does that reassure you, or are you seeing a subtlety that I'm overlooking in that analysis?

2025-01-15 18:51 UTC, bradcray commented on third-party/gasnet/Makefile
> +	$(ENSURE_GASNET_COMPATIBLE_COMPILER) cd $(GASNET_BUILD_DIR) && $(CHPL_GASNET_ENV_VARS) $(GASNET_SUBDIR)/$(CHPL_GASNET_CFG_SCRIPT) --prefix=$(GASNET_INSTALL_DIR) --disable-seq --enable-par --disable-
Sheesh I'm embarrassed about how long that PR has been sitting there.  I may have mentioned this before, but we're generally not as good about monitoring new PRs unless they're pointed out to us as we are issues and questions in other forums, so definitely feel free to ping someone / us / me on a PR to get attention to it.  Or maybe you did that off the PR and someone just dropped the ball…  Anyway, thanks for pointing that out.

2025-01-15 19:36 UTC, bonachea commented on third-party/gasnet/Makefile
> +	$(ENSURE_GASNET_COMPATIBLE_COMPILER) cd $(GASNET_BUILD_DIR) && $(CHPL_GASNET_ENV_VARS) $(GASNET_SUBDIR)/$(CHPL_GASNET_CFG_SCRIPT) --prefix=$(GASNET_INSTALL_DIR) --disable-seq --enable-par --disable-
Feel free to review/merge #25414 yourself now that it's been pointed out ;-)

2025-01-15 19:37 UTC, bonachea commented on runtime/src/tasks/qthreads/tasks-qthreads.c
> +            chpl_warning(msg, 0, 0);
@bradcray Thanks for the context. 

> expect this logic to fire on every locale, and therefore to potentially take different actions on different locales. To check that theory, I put a printf() into the code here, ran a hello world on 4 locales, and got the message printed 4 times. Does that reassure you, or are you seeing a subtlety that I'm overlooking in that analysis?

FWIW the logic I was specifically referring to is the invocation of `chpl_warning()` on line 513 which is conditional on line 505: `if (chpl_nodeID == 0) {` .  Are you saying that `chpl_nodeID` is zero on all locales? 

As I said in my initial comment, I'm fine with dropping this observation entirely in light of Chapel's position on heterogeneous systems. I was really just noting it for completeness.

2025-01-15 22:03 UTC, bradcray commented on runtime/src/tasks/qthreads/tasks-qthreads.c
> +            chpl_warning(msg, 0, 0);
[of course, the downside to my statement is that we'll probably get a message per locale on homogeneous systems where we hit this, which may be overkill and regrettable, but still feels like an improvement over the status quo]

2025-01-15 23:36 UTC, bradcray commented on runtime/src/tasks/qthreads/tasks-qthreads.c
> +            chpl_warning(msg, 0, 0);
[whoops, made the above comment without seeing your earlier response.  I think I must've been in an un-refreshed browser tab]

> FWIW the logic I was specifically referring to is the invocation of chpl_warning() on line 513 which is conditional on line 505: if (chpl_nodeID == 0) { . Are you saying that chpl_nodeID is zero on all locales?

Oh, duh… 🤦  And of course I put my printf outside of that conditional rather than within it.  :P

I think I'm inclined to proceed with the PR as-is for simplicity and due to not really being aware of realistic heterogeneous use cases (combined with a hope that, with the new setting, we'll hit this conditional far less often than we would've had it been here before, with the configuration changes).

2025-01-15 23:37 UTC, bradcray commented on third-party/gasnet/Makefile
> +	$(ENSURE_GASNET_COMPATIBLE_COMPILER) cd $(GASNET_BUILD_DIR) && $(CHPL_GASNET_ENV_VARS) $(GASNET_SUBDIR)/$(CHPL_GASNET_CFG_SCRIPT) --prefix=$(GASNET_INSTALL_DIR) --disable-seq --enable-par --disable-
Before seeing this, I pulled your other change from that into this PR and added contributor credit for you to this one, mostly based on your previous comment and because it seemed simpler.

2025-01-15 23:46 UTC, jabraham17 approved these changes

2025-01-15 23:46 UTC, jabraham17 commented on runtime/src/tasks/qthreads/tasks-qthreads.c
> +                     "If using CHPL_COMM=gasnet, set 'GASNET_MAX_THREADS' to "
I think this would be better if it just check against `CHPL_COMM` to specialize the error message for GASNet. But my understanding of this PR is that in practice this warning can only occur with GASNet, so I say leave it unless we see it occur on non-gasnet systems

2025-01-15 23:53 UTC, bonachea approved these changes

2025-01-15 23:53 UTC, bonachea commented on runtime/src/tasks/qthreads/tasks-qthreads.c
> +            chpl_warning(msg, 0, 0);
I share your hope and agree this seems like a reasonable resolution.

2025-01-15 23:53 UTC, bonachea commented on third-party/gasnet/Makefile
> +	$(ENSURE_GASNET_COMPATIBLE_COMPILER) cd $(GASNET_BUILD_DIR) && $(CHPL_GASNET_ENV_VARS) $(GASNET_SUBDIR)/$(CHPL_GASNET_CFG_SCRIPT) --prefix=$(GASNET_INSTALL_DIR) --disable-seq --enable-par --disable-
Works for me, I'll close the other PR.

2025-01-15 23:53 UTC, bonachea commented on third-party/gasnet/Makefile
> +
I should note in passing that the same defect repaired by the `.PHONY` directive above for third-party/gasnet/Makefile alone also impacts many other Makefiles in the Chapel repo. I just didn't feel I had the authority to propose adding this to all of them ;-)

2025-01-15 23:53 UTC, bonachea commented on runtime/src/tasks/qthreads/tasks-qthreads.c
> +                     "If using CHPL_COMM=gasnet, set 'GASNET_MAX_THREADS' to "
>  in practice this warning can only occur with GASNet

I believe that's accurate for today's backends.

2025-01-15 23:57 UTC, bradcray commented on third-party/gasnet/Makefile
> +
Yeah, I've felt long aware of that as well.  Though I'm also not remembering the consequences of not listing it in a `.PHONY` (and the fact that it hasn't seemed to bite us has prevented me from doing anything to improve the situation).  Can you remind me?

2025-01-15 23:59 UTC, bradcray commented on runtime/src/tasks/qthreads/tasks-qthreads.c
> +                     "If using CHPL_COMM=gasnet, set 'GASNET_MAX_THREADS' to "
> I think this would be better if it just checks against CHPL_COMM

I agree that'd be better.  In putting this together very rapidly, I couldn't remember how to check `CHPL_COMM` within the runtime, nor how easy it was, and was apparently too lazy to look.  Now that Jade's reminded me, I'm going to tighten this up, less because I think it'll ever happen in practice (well, in the near-term anyway) and more because I don't really like the "If…" conditional in the warning when we really ought to know the answer.

2025-01-16 00:07 UTC, bonachea commented on third-party/gasnet/Makefile
> +
Here is the [GNU documentation for PHONY targets](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html).

The intent of the `FORCE` target used throughout Chapel Makefiles is to ensure that any rule encountered with `FORCE` as a prerequisite will always have its recipe executed, regardless of filesystem state.

However in failing to declare `FORCE` with a `.PHONY` directive, it means that if a user happens to have a file called `"FORCE"` in any directory containing such a Makefile (ie in the Chapel source tree), that Makefile might no longer operate as intended (seeing the on-disk file as confirmation that `FORCE` is up-to-date and then skip remaking any dependent rules). So for example in this case the `clean`, `cleanall` and `clobber` Makefile targets would become no-ops in a directory containing a stray file called `"FORCE"`.

It's admittedly a perverse/unusual use case, but it's also exactly what `.PHONY` is designed to concisely mitigate and IMHO it's best-practice for such targets in Makefiles.

2025-01-16 00:09 UTC, bradcray commented on third-party/gasnet/Makefile
> +
Got it, and thanks for the lesson.  Makes complete sense.

2025-01-16 00:13 UTC, bradcray commented on third-party/gasnet/Makefile
> +
I've opened https://github.com/chapel-lang/chapel/issues/26548 for this.

2025-01-16 00:33 UTC, bradcray commented on runtime/src/tasks/qthreads/tasks-qthreads.c
> +                     "If using CHPL_COMM=gasnet, set 'GASNET_MAX_THREADS' to "
Improved this in https://github.com/chapel-lang/chapel/pull/26448/commits/d44edd2a8559f719ffa5789260a4f147bc6d66ee and caught/fixed a longstanding bug in testing it.

2025-01-16 00:35 UTC, jabraham17 approved these changes

2025-01-16 03:46 UTC, bonachea requested changes
Noted one minor potential defect, otherwise LGTM!

2025-01-16 03:46 UTC, bonachea commented on runtime/src/comm/gasnet/comm-gasnet-ex.c
> +  uint64_t maxGasnetThreads = gex_System_QueryMaxThreads();
@bradcray Thanks for noticing and fixing this closely related defect! 

For the record: the previous code was (mostly) correct for the default GASNet configuration where the soft and hard client thread limits are equally 256 (it was also the only option back in GASNet-1 days when this code was initially written).  Now that this PR raises the hard limit at configure time, the soft and hard limits are no longer equal so the difference matters, and this GASNet-EX query returns this process's soft limit that is in force at runtime, which is what we actually need this function to return.

One minor quibble: 
IIUC The prior code used `GASNETI_MAX_THREADS-1` because the `-1` was reserving one thread (the primordial one that runs `chpl_comm_init()`) for use by the Chapel runtime, leaving the rest available for creation by the tasking layer (the consumer of the value we are returning here). I suspect we still need to reserve that one thread to avoid an off-by-one error in our accounting of total threads that might eventually invoke a GASNet call.

TL;DR:

```suggestion
  uint64_t maxGasnetThreads = gex_System_QueryMaxThreads() - 1;
```

2025-01-17 00:24 UTC, bonachea commented on runtime/src/comm/gasnet/comm-gasnet-ex.c
> +  uint64_t maxGasnetThreads = gex_System_QueryMaxThreads();
This is resolved (in a slightly different manner) by 465e173

2025-01-17 00:24 UTC, bonachea approved these changes
LGTM!

2025-01-17 00:29 UTC, merged